name = "worker-dev"
main = "src/index.ts"
compatibility_date = "2022-11-28"
compatibility_flags = []

kv_namespaces = [
    { binding = "WORKER_DATA", id = "d650cb4bcb834d46b44e6deddf4a6580", preview_id = "c53806a7346e449aa95d9f9958ccaa09" },
]

[vars]
FAUNA_DOMAIN = "localhost"
FAUNA_SCHEME = "http"
FAUNA_PORT = 8443

[env.production]
name = "worker-dev-prod"

[env.production.vars]
FAUNA_DOMAIN = "db.us.fauna.com"
FAUNA_SCHEME = "https"
FAUNA_PORT = 443

# The necessary secrets are:
# - FAUNA_KEY
# Run `echo <VALUE> | npx wrangler secret put <NAME> --env production` for each of these