name = "fitbit-worker-dev"
main = "src/index.ts"
compatibility_date = "2022-11-28"
compatibility_flags = []

kv_namespaces = [
    { binding = "WORKER_DATA", id = "b954d632e8b94ec8bb50f5f53691381a", preview_id = "2bc3450964f049b1921ca95993b260e4" },
]

[vars]
FAUNA_DOMAIN = "localhost"
FAUNA_SCHEME = "http"
FAUNA_PORT = 8443

[env.production]
name = "fitbit-worker"

[env.production.vars]
FAUNA_DOMAIN = "db.us.fauna.com"
FAUNA_SCHEME = "https"
FAUNA_PORT = 443

# The necessary secrets are:
# - FAUNA_KEY
# Run `echo <VALUE> | npx wrangler secret put <NAME> --env production` for each of these