name = "fitbit-worker"
main = "src/index.ts"
compatibility_date = "2022-11-28"
compatibility_flags = []
kv_namespaces = [
    { binding = "WORKER_DATA", id = "b954d632e8b94ec8bb50f5f53691381a" }
]

[triggers]
crons = ["0 */6 * * *"]

[vars]
FAUNA_DOMAIN = "db.us.fauna.com"
FAUNA_SCHEME = "https"
FAUNA_PORT = 443

[env.dev]
kv_namespaces = [
    { binding = "WORKER_DATA", id = "N/A", preview_id = "N/A" },
]

[env.dev.vars]
FAUNA_DOMAIN = "localhost"
FAUNA_SCHEME = "http"
FAUNA_PORT = 8443

[env.dev.triggers]
crons = ["* * * * *"]