name = "fitbit-worker"
main = "src/index.ts"
compatibility_date = "2022-11-28"
compatibility_flags = []
kv_namespaces = [
    { binding = "WORKER_DATA", id = "b954d632e8b94ec8bb50f5f53691381a", preview_id = "2d519e2907f94aae9af2549a1c217afb"}
]

[vars]
FAUNA_DOMAIN = "db.us.fauna.com"
FAUNA_SCHEME = "https"
FAUNA_PORT = 443

[env.dev]
kv_namespaces = [
    { binding = "example", id = "***", preview_id = "***" },
]

[env.dev.vars]
FAUNA_DOMAIN = "localhost"
FAUNA_SCHEME = "http"
FAUNA_PORT = 8443

# The necessary secrets are:
# - FAUNA_KEY
# Run `echo <VALUE> | npx wrangler secret put <NAME> --env production` for each of these