name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          command: publish --env=production
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            FAUNA_KEY
        env:
          FAUNA_KEY: ${{ secrets.FAUNA_KEY }}
